### 授权码模式
POST localhost:53070/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=authorization_code&code=W34ttV&redirect_uri=http://localhost/

### 密码模式
POST localhost:53070/auth/oauth/token?client_id=XcWebApp&client_secret=XcWebApp&grant_type=password&username={"username":"Kyle","password":"111111","authType":"password","checkcode":"L8OJ"}

### 校验JWT令牌
POST localhost:53070/auth/oauth/check_token?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiS2lraVwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJLeWxlXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3ODUyODY4OSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI3YWJjMDZhMS1jNDBhLTRkOWMtYWQ3Yy05MmFhOTliYTk0ODAiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.BHId8cWjIL7cDglY7nhx3T4gc5vlYmtbuUO9Fvzn5Ls

### 根据课程id查询课程基本信息
GET localhost:53040/content/course/40
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdWQiOlsieHVlY2hlbmctcGx1cyJdLCJ1c2VyX25hbWUiOiJ7XCJjb21wYW55SWRcIjpcIjEyMzIxNDE0MjVcIixcImNyZWF0ZVRpbWVcIjpcIjIwMjItMDktMjhUMDg6MzI6MDNcIixcImlkXCI6XCI1MlwiLFwibmFtZVwiOlwiS2lraVwiLFwicGVybWlzc2lvbnNcIjpbXSxcInNleFwiOlwiMVwiLFwic3RhdHVzXCI6XCJcIixcInVzZXJuYW1lXCI6XCJLeWxlXCIsXCJ1dHlwZVwiOlwiMTAxMDAyXCJ9Iiwic2NvcGUiOlsiYWxsIl0sImV4cCI6MTY3ODUyODY4OSwiYXV0aG9yaXRpZXMiOlsidGVzdCJdLCJqdGkiOiI3YWJjMDZhMS1jNDBhLTRkOWMtYWQ3Yy05MmFhOTliYTk0ODAiLCJjbGllbnRfaWQiOiJYY1dlYkFwcCJ9.BHId8cWjIL7cDglY7nhx3T4gc5vlYmtbuUO9Fvzn5Ls