### 课程查询列表
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "",
  "publishStatus": ""
}

### 课程分类查询
GET {{content_host}}/content//course-category/tree-nodes?id=1
Content-Type: application/json

### 新增课程
POST {{content_host}}/content/course
Content-Type: application/json

{
  "mt": "1-1",
  "st": "1-1-1",
  "name": "123",
  "pic": "",
  "teachmode": "200002",
  "users": "初级人员",
  "tags": "",
  "grade": "204001",
  "description": "这是一门测试课程",
  "charge": "201001",
  "price": -99,
  "originalPrice": -999,
  "qq": "123564",
  "wechat": "123654",
  "phone": "156213",
  "validDays": 365
}