### 课程查询列表
POST {{content_host}}/content/course/list?pageNo=1&pageSize=2
Content-Type: application/json

{
  "auditStatus": "",
  "courseName": "",
  "publishStatus": ""
}

### 课程分类查询
GET {{content_host}}/content//course-category/tree-nodes?id=1
Content-Type: application/json

